# Generated by Django 3.1.14 on 2022-02-01 11:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0218_rm_unused_gcp_partables")]

    operations = [
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary", name="all_labels", field=models.JSONField(null=True)
        )
    ]
